from django.db import models

# Create your models here.
class Expense(models.Model):
    """Model representing an expense incurred by the laundry service."""
    EXPENSE_TYPE_CHOICES = [
        ('soap', 'Soap'),
        ('water', 'Water'),
        ('electricity', 'Electricity'),
        ('rent', 'Rent'),
        ('salaries', 'Salaries'),
        ('maintenance', 'Maintenance'),
        ('miscellaneous', 'Miscellaneous'),
    ]
    branch = models.ForeignKey('branches.Branch', on_delete=models.CASCADE, related_name='expenses')
    expense_type = models.CharField(max_length=20, choices=EXPENSE_TYPE_CHOICES)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)
    date_incurred = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.description} - {self.amount} on {self.date_incurred}"

class Income(models.Model):
    """Model representing revenue generated by the laundry service."""
    INCOME_SOURCE_CHOICES = [
        ('service', 'Service Fees'),
        ('product_sales', 'Product Sales'),
        ('promotions', 'Promotions'),
        ('loans', 'Loans'),
        ('investments', 'Investments'),
        ('capital', 'Capital'),
        ('other', 'Other'),
    ]
    source = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_received = models.DateField(auto_now_add=True)
    branch = models.ForeignKey('branches.Branch', on_delete=models.CASCADE, related_name='incomes')

    def __str__(self):
        return f"{self.source} - {self.amount} on {self.date_received}"