from django.db import models

# Expense Category
class ExpenseCategory(models.Model):
    """Model representing a category of expense."""
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return str(self.name)


# Expense Model
class Expense(models.Model):
    """Model representing an expense incurred by the laundry service."""
    branch = models.ForeignKey('branches.Branch', on_delete=models.CASCADE, related_name='expenses')
    category = models.ForeignKey(ExpenseCategory, on_delete=models.SET_NULL, null=True, related_name='expenses')
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)
    date_incurred = models.DateField()

    def __str__(self):
        return f"{self.category} - {self.amount} on {self.date_incurred}"


# Income Category
class IncomeCategory(models.Model):
    """Model representing a category of income."""
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return str(self.name)


# Income Model
class Income(models.Model):
    """Model representing revenue generated by the laundry service."""
    branch = models.ForeignKey('branches.Branch', on_delete=models.CASCADE, related_name='incomes')
    category = models.ForeignKey(IncomeCategory, on_delete=models.SET_NULL, null=True, related_name='incomes')
    description = models.TextField(blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date_received = models.DateField()

    def __str__(self):
        return f"{self.category} - {self.amount} on {self.date_received}"