# Generated by Django 5.2.4 on 2025-09-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_requested',
            new_name='is_urgent',
        ),
    ]
