# Generated by Django 5.2.4 on 2025-09-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_address_order_delivery_map_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
