# Generated by Django 5.2.8 on 2025-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_delivery_time_alter_order_pickup_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_map_link',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_map_link',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
