# Generated by Django 5.2.5 on 2025-12-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_add_partially_paid_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, choices=[('early_morning', 'Early Morning (6am - 9am)'), ('late_morning', 'Late Morning (9am - 12pm)'), ('early_afternoon', 'Early Afternoon (12pm - 3pm)'), ('late_afternoon', 'Late Afternoon (3pm - 6pm)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, choices=[('early_morning', 'Early Morning (6am - 9am)'), ('late_morning', 'Late Morning (9am - 12pm)'), ('early_afternoon', 'Early Afternoon (12pm - 3pm)'), ('late_afternoon', 'Late Afternoon (3pm - 6pm)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_time',
            field=models.CharField(choices=[('early_morning', 'Early Morning (6am - 9am)'), ('late_morning', 'Late Morning (9am - 12pm)'), ('early_afternoon', 'Early Afternoon (12pm - 3pm)'), ('late_afternoon', 'Late Afternoon (3pm - 6pm)')], default='late_afternoon', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
