# Generated by Django 5.2.5 on 2025-12-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_time_order_pickup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
