# Generated by Django 5.2.5 on 2025-12-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_delivery_date_alter_order_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('dropped by user', 'Dropped by User'), ('pending pickup', 'Pending Pickup'), ('picked up', 'Picked Up'), ('sent to wash', 'Sent to Wash'), ('in wash', 'In Wash'), ('washed', 'Washed'), ('picked by client', 'Picked by Client'), ('pending delivery', 'Pending Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='dropped by user', max_length=20),
        ),
    ]
