# Generated by Django 5.2.8 on 2025-12-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='wash_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
