# Generated by Django 5.2.4 on 2025-09-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_expensecategory_incomecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_incurred',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='date_received',
            field=models.DateField(),
        ),
    ]
