# Generated by Django 5.2.1 on 2025-05-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LaundryService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description_en", models.TextField()),
                ("description_hi", models.TextField(blank=True, null=True)),
                ("description_ne", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
