# Generated by Django 5.2.4 on 2025-07-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('individual', 'Individual Clothes'), ('bulk', 'Bulk (kg)'), ('hybrid', 'Hybrid')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_description', models.CharField(max_length=100)),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=7)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_clothes', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='BulkCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_type', models.CharField(max_length=100)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_clothes', to='services.service')),
            ],
        ),
    ]
