# Generated by Django 5.2.5 on 2025-12-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_deliverytype_washtype_alter_service_id_servicecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClothType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_cost', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('urgent_cost', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='washtype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('cloth_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='services.clothname')),
                ('cloth_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='services.clothtype')),
                ('wash_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='services.washtype')),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'unique_together': {('wash_type', 'cloth_name', 'cloth_type')},
            },
        ),
    ]
