# Generated by Django 5.2.4 on 2025-07-23 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch_id', models.CharField(max_length=10, unique=True)),
                ('branch_manager', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('manager_id', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hired_date', models.DateField()),
                ('leaving_date', models.DateField()),
                ('id_type', models.CharField(choices=[('citizenship', 'Citizenship'), ('national_id', 'National Id'), ('drivers_licence', "Driver's Licence")], max_length=20)),
                ('citizenship_number', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='branches.branch')),
            ],
            options={
                'db_table': 'branch_managers',
            },
        ),
    ]
