# Generated by Django 5.2.4 on 2025-09-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_address_branch_city_branch_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
