# Generated by Django 5.2.4 on 2025-09-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
