# Generated by Django 5.2.8 on 2025-12-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchmanager',
            name='id_type',
            field=models.CharField(choices=[('citizenship', 'Citizenship'), ('national_id', 'National Id'), ('drivers_licence', "Driver's Licence"), ('passport', 'Passport')], max_length=20),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branchmanager',
            name='manager_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
