# Generated by Django 5.2.4 on 2025-09-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_data',
            field=models.JSONField(blank=True, help_text='Order data to create order after payment', null=True),
        ),
    ]
