# Generated by Django 5.2.5 on 2025-12-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_map_link'),
        ('payments', '0006_payment_idempotency_key_payment_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='branches.branch'),
        ),
    ]
