# Generated by Django 5.2.8 on 2025-12-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_source',
            field=models.CharField(default='payment_page', help_text="Source of payment: 'order' or 'payment_page'", max_length=20),
        ),
    ]
