# Generated by Django 5.2.8 on 2025-12-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_expense_date_incurred_and_more'),
        ('payments', '0008_payment_payment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='income_record',
            field=models.OneToOneField(blank=True, help_text='Income record created from this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='accounting.income'),
        ),
    ]
