# Generated by Django 5.2.4 on 2025-09-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('branch_manager', 'Branch Manager'), ('rider', 'Rider'), ('customer', 'Customer'), ('accountant', 'Accountant')], default='customer', max_length=20),
        ),
    ]
