# Generated by Django 5.2.4 on 2025-09-01 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
