# Generated by Django 5.2.8 on 2025-12-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('branch_manager', 'Branch Manager'), ('rider', 'Rider'), ('customer', 'Customer'), ('accountant', 'Accountant')], default='customer', max_length=15),
        ),
    ]
