# Generated by Django 5.2.8 on 2025-12-05 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
