# Generated by Django 5.2.5 on 2025-12-13 18:07

from django.db import migrations


def update_admin_flags(apps, schema_editor):
    """Update is_staff and is_superuser flags for admin and branch_manager users."""
    User = apps.get_model('users', 'User')
    
    # Update admin users
    User.objects.filter(role='admin').update(is_staff=True, is_superuser=True)
    
    # Update branch_manager users
    User.objects.filter(role='branch_manager').update(is_staff=True)


def reverse_admin_flags(apps, schema_editor):
    """Reverse the migration (optional)."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_vip'),
    ]

    operations = [
        migrations.RunPython(update_admin_flags, reverse_admin_flags),
    ]
